# Generated by Django 4.2 on 2023-05-03 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 10, 54, 29, 897106, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.EmailField(default='qw@mil.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='phone',
            field=models.CharField(default='55533556644', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='who_book',
            field=models.CharField(default='aidai', max_length=30),
            preserve_default=False,
        ),
    ]
